# name: Deploy to EC2  

# on:
#   push:
#     branches:
#       - develop 

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: temurin
#         java-version: '17'

#     - name: Give Gradle wrapper permission
#       run: chmod +x ./gradlew

#     - name: Build with Gradle
#       run: ./gradlew build

#     - name: Copy JAR to EC2
#       uses: appleboy/scp-action@v0.1.7
#       with:
#         host: 3.94.211.213
#         username: ec2-user
#         key: ${{ secrets.EC2_KEY }}
#         source: build/libs/studyhub-backend-0.0.1-SNAPSHOT.jar
#         target: /home/ec2-user/

#     - name: Restart server on EC2
#       uses: appleboy/ssh-action@v0.1.7
#       with:
#         host: 3.94.211.213
#         username: ec2-user
#         key: ${{ secrets.EC2_KEY }}
#         script: |
#           pkill -f studyhub-backend-0.0.1-SNAPSHOT.jar || true
#           setsid nohup java -jar /home/ec2-user/studyhub-backend-0.0.1-SNAPSHOT.jar > backend.log 2>&1 < /dev/null &